const $=(q,r=document)=>r.querySelector(q);
const $$=(q,r=document)=>[...r.querySelectorAll(q)];
const fmt=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
let state={mode:'loading',contracts:[],receivables:[],findings:[],recoveries:[]};
let view='dashboard';
const icons={overdue:'◷',renewal:'↻',adjustment:'%',adjustment_review:'?',underbilling:'↓',scope:'⌁'};
const labels={overdue:'Inadimplência',renewal:'Renovação',adjustment:'Reajuste',adjustment_review:'Validar reajuste',underbilling:'Subfaturamento',scope:'Escopo extra'};
const money=v=>fmt.format(Number(v||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dbr=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const remaining=x=>Math.max(0,Number(x?.estimated_value||0)-Number(x?.recovered||0));
function toast(msg,type=''){const x=document.createElement('div');x.className='toast '+type;x.textContent=msg;$('#toast').append(x);setTimeout(()=>x.remove(),3200)}
async function api(action=null,payload={}){const opt=action?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})}:{};const r=await fetch('/api/app',opt);const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha na API');return j}
async function load(silent=false){if(!silent)$('#content').innerHTML='<div class="loading-card">Sincronizando dados do Recovr...</div>';try{state=await api();$('#cloudState').textContent=state.mode==='cloud'?'● banco conectado':'● demonstração local';render()}catch(e){toast(e.message,'error');$('#content').innerHTML='<div class="empty">Não foi possível carregar os dados. Tente atualizar.</div>'}}
function openApp(){$('#landing').classList.add('hidden');$('#app').classList.remove('hidden');load()}
function setView(v){view=v;$$('#sideNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const titles={dashboard:'Visão geral',findings:'Oportunidades',contracts:'Contratos',receivables:'Contas a receber',scope:'Scope Intelligence'};$('#pageTitle').textContent=titles[v];$('#crumb').textContent='RECOVR / '+titles[v].toUpperCase();render();$('.sidebar').classList.remove('open')}
function metrics(){const open=state.findings.filter(x=>['open','action'].includes(x.status));const potential=open.reduce((a,x)=>a+remaining(x),0);const recovered=state.recoveries.reduce((a,x)=>a+Number(x.amount||0),0);const overdue=state.receivables.filter(x=>!x.paid_at&&new Date(x.due_date)<new Date()).reduce((a,x)=>a+Number(x.amount||0),0);return{potential,recovered,overdue,open:open.length}}
function render(){if($('#app').classList.contains('hidden'))return;const m=metrics();$('#navCount').textContent=m.open;const f={dashboard:renderDashboard,findings:renderFindings,contracts:renderContracts,receivables:renderReceivables,scope:renderScope}[view]||renderDashboard;$('#content').innerHTML=f(m)}
function metricGrid(m){return `<div class="metric-grid"><div class="metric highlight"><label>Potencial recuperável</label><strong>${money(m.potential)}</strong><small>${m.open} oportunidades abertas · saldo restante</small></div><div class="metric"><label>Já recuperado</label><strong>${money(m.recovered)}</strong><small>confirmado no histórico</small></div><div class="metric"><label>Em atraso</label><strong>${money(m.overdue)}</strong><small>contas vencidas</small></div><div class="metric"><label>Contratos ativos</label><strong>${state.contracts.length}</strong><small>monitorados pelo motor</small></div></div>`}
function impactCell(x){if(Number(x.estimated_value)<=0)return 'A validar';const left=remaining(x),rec=Number(x.recovered||0);return rec>0?`<strong>${money(left)}</strong><small class="sub">${money(rec)} já recuperados</small>`:money(left)}
function findingRows(limit=99){const arr=state.findings.filter(x=>x.status!=='dismissed').slice(0,limit);if(!arr.length)return '<tr><td colspan="5"><div class="empty">Nenhuma oportunidade encontrada.</div></td></tr>';return arr.map(x=>`<tr class="clickable" data-finding="${x.id}"><td><div class="detector"><span class="type-icon">${icons[x.detector_type]||'◎'}</span><span><b>${esc(x.title)}</b><small class="sub">${labels[x.detector_type]||x.detector_type}</small></span></div></td><td><span class="client">${esc(x.client||'—')}</span></td><td class="money">${impactCell(x)}</td><td><span class="pill ${x.status}">${x.status==='open'?'Aberta':x.status==='action'?'Em ação':x.status==='recovered'?'Recuperada':'Ignorada'}</span></td><td>${Math.round(Number(x.confidence||0))}%</td></tr>`).join('')}
function renderDashboard(m){return `${metricGrid(m)}<section class="section"><div class="section-head"><div><h3>Oportunidades prioritárias</h3><p>O que merece atenção agora</p></div><button class="btn ghost" data-view="findings">Ver todas</button></div><div style="overflow:auto"><table class="table"><thead><tr><th>Descoberta</th><th>Cliente</th><th>Impacto restante</th><th>Status</th><th>Conf.</th></tr></thead><tbody>${findingRows(6)}</tbody></table></div></section><div class="two-col"><section class="section"><div class="section-head"><div><h3>Como o Recovr pensa</h3><p>IA interpreta. Regras calculam.</p></div></div><div style="padding:18px"><div class="action-card"><h4>1. Detecta</h4><p>Cruza vencimentos, vigência, reajustes e valores faturados.</p></div><div class="action-card" style="margin-top:10px"><h4>2. Prova</h4><p>Cada descoberta precisa de evidência e cálculo auditável.</p></div><div class="action-card" style="margin-top:10px"><h4>3. Recupera</h4><p>Registra ação e mede somente o dinheiro realmente recuperado.</p></div></div></section><section class="section"><div class="section-head"><div><h3>Próximo melhor passo</h3><p>Recomendação operacional</p></div></div><div style="padding:18px"><div class="scope-result"><h4>✦ Rode uma nova análise</h4><p style="color:#9aa8b8;font-size:12px;line-height:1.6">O motor verifica inadimplência, renovação, reajuste e subfaturamento com os dados mais recentes.</p><button class="btn primary" data-action="run-analysis" style="margin-top:12px">Analisar agora</button></div></div></section></div>`}
function renderFindings(){return `<section class="section" style="margin-top:0"><div class="section-head"><div><h3>Receita encontrada</h3><p>Clique para abrir evidências, cálculo e recuperação.</p></div><button class="btn primary" data-action="run-analysis">✦ Rodar análise</button></div><div style="overflow:auto"><table class="table"><thead><tr><th>Descoberta</th><th>Cliente</th><th>Impacto restante</th><th>Status</th><th>Conf.</th></tr></thead><tbody>${findingRows()}</tbody></table></div></section>`}
function renderContracts(){return `<section class="section" style="margin-top:0"><div class="section-head"><div><h3>Contratos monitorados</h3><p>Base para reajuste, renovação, faturamento e escopo.</p></div><button class="btn primary" data-action="new-contract">+ Novo contrato</button></div><div style="overflow:auto"><table class="table"><thead><tr><th>Cliente</th><th>Mensalidade</th><th>Fim</th><th>Reajuste</th></tr></thead><tbody>${state.contracts.map(c=>`<tr><td><b>${esc(c.client)}</b><small class="sub">${esc(c.title||'Contrato de serviços')}</small></td><td class="money">${money(c.current_value)}</td><td>${dbr(c.end_date)}</td><td>${esc(c.adjustment_index||'—')}</td></tr>`).join('')||'<tr><td colspan="4"><div class="empty">Nenhum contrato.</div></td></tr>'}</tbody></table></div></section>`}
function renderReceivables(){return `<section class="section" style="margin-top:0"><div class="section-head"><div><h3>Contas a receber</h3><p>Base para inadimplência e divergência de cobrança.</p></div><button class="btn primary" data-action="new-receivable">+ Nova cobrança</button></div><div style="overflow:auto"><table class="table"><thead><tr><th>Cliente</th><th>Descrição</th><th>Valor</th><th>Vencimento</th><th>Status</th></tr></thead><tbody>${state.receivables.map(r=>`<tr><td><b>${esc(r.client)}</b></td><td>${esc(r.description||'Cobrança')}</td><td class="money">${money(r.amount)}</td><td>${dbr(r.due_date)}</td><td>${r.paid_at?'<span class="pill recovered">Pago</span>':'<span class="pill open">Pendente</span>'}</td></tr>`).join('')||'<tr><td colspan="5"><div class="empty">Nenhuma cobrança.</div></td></tr>'}</tbody></table></div></section>`}
function renderScope(){return `<div class="two-col"><section class="section" style="margin-top:0"><div class="section-head"><div><h3>Detector de trabalho não cobrado</h3><p>Compare uma solicitação com o contrato.</p></div></div><form id="scopeForm" style="padding:20px" class="form-grid"><label class="field full"><span>Contrato</span><select name="contract_id" required><option value="">Selecione</option>${state.contracts.map(c=>`<option value="${c.id}">${esc(c.client)} — ${money(c.current_value)}/mês</option>`).join('')}</select></label><label class="field"><span>Origem</span><select name="source"><option>WhatsApp</option><option>E-mail</option><option>Reunião</option><option>Tarefa</option><option>Manual</option></select></label><label class="field"><span>Valor já conhecido</span><input name="value" type="number" min="0" step="0.01" placeholder="0,00"></label><label class="field"><span>Horas estimadas</span><input name="hours" type="number" min="0" step="0.25"></label><label class="field"><span>Valor / hora</span><input name="hourly" type="number" min="0" step="0.01"></label><label class="field full"><span>Pedido / atividade do cliente</span><textarea name="activity" rows="6" required placeholder="Ex.: Preciso também de uma landing page, 12 banners e edição das fotos..."></textarea></label><div class="field full"><button class="btn primary" type="submit">✦ Comparar com contrato</button></div></form></section><section class="section" style="margin-top:0"><div class="section-head"><div><h3>Por que isso importa</h3><p>Scope creep destrói margem sem aparecer no financeiro.</p></div></div><div style="padding:20px"><div class="action-card"><h4>Contrato</h4><p>Define o que foi realmente vendido e por qual valor.</p></div><div class="action-card" style="margin-top:10px"><h4>Atividade</h4><p>Mostra o que o cliente efetivamente pediu ao time.</p></div><div class="action-card" style="margin-top:10px"><h4>Recovr</h4><p>Classifica aderência e só calcula R$ com preço informado ou horas × valor/hora.</p></div></div></section></div>`}
function modal(html){$('#modal').innerHTML=`<div class="modal-backdrop"><div class="modal">${html}</div></div>`}
function closeModal(){$('#modal').innerHTML=''}
function findingModal(id){const x=state.findings.find(f=>String(f.id)===String(id));if(!x)return;const meta=x.metadata||{};const recovered=Number(x.recovered||0);const left=remaining(x);modal(`<div class="modal-head"><div><small style="color:var(--muted)">${labels[x.detector_type]||x.detector_type} · ${Math.round(Number(x.confidence||0))}% confiança</small><h3>${esc(x.title)}</h3></div><button class="close" data-action="close-modal">×</button></div><div class="modal-body"><div class="metric-grid" style="grid-template-columns:repeat(3,1fr)"><div class="metric"><label>Potencial original</label><strong style="font-size:21px">${Number(x.estimated_value)>0?money(x.estimated_value):'A validar'}</strong></div><div class="metric"><label>Recuperado</label><strong style="font-size:21px">${money(recovered)}</strong></div><div class="metric"><label>Restante</label><strong style="font-size:21px">${Number(x.estimated_value)>0?money(left):'—'}</strong></div></div><h4>Evidências</h4>${(x.evidence||[]).map(e=>`<div class="evidence"><strong>${esc(e.label)}</strong><p>${esc(e.excerpt||'')}</p></div>`).join('')||'<div class="evidence"><p>'+esc(x.summary||'Sem evidência textual adicional.')+'</p></div>'}<h4>Cálculo</h4><div class="calc">${esc(meta.calculation?.formula||meta.formula||'Estimativa baseada nos dados disponíveis.')} ${meta.calculation?.result!=null?' → '+money(meta.calculation.result):''}</div></div><div class="modal-actions"><button class="btn ghost" data-action="dismiss-finding" data-id="${x.id}">Ignorar</button><button class="btn ghost" data-action="start-finding" data-id="${x.id}">Marcar em ação</button>${left>0?`<button class="btn primary" data-action="recover-finding" data-id="${x.id}">Registrar recuperação</button>`:''}</div>`)}
function newContract(){modal(`<form id="contractForm"><div class="modal-head"><h3>Novo contrato</h3><button type="button" class="close" data-action="close-modal">×</button></div><div class="modal-body form-grid"><label class="field full"><span>Cliente</span><input name="client" required></label><label class="field"><span>Valor mensal</span><input name="value" type="number" required></label><label class="field"><span>Fim do contrato</span><input name="end" type="date" required></label><label class="field"><span>Reajuste</span><input name="adjustment" placeholder="Ex.: 5,5% anual / IPCA"></label><label class="field"><span>Último reajuste</span><input name="last_adjustment" type="date"></label><label class="field full"><span>Escopo</span><textarea name="scope" rows="4" placeholder="Entregáveis incluídos no contrato"></textarea></label></div><div class="modal-actions"><button class="btn ghost" type="button" data-action="contract-ai">Ler PDF com IA</button><button class="btn primary">Salvar contrato</button></div></form>`)}
function newReceivable(){modal(`<form id="receivableForm"><div class="modal-head"><h3>Nova cobrança</h3><button type="button" class="close" data-action="close-modal">×</button></div><div class="modal-body form-grid"><label class="field full"><span>Cliente</span><input name="client" required></label><label class="field full"><span>Descrição</span><input name="description" required></label><label class="field"><span>Valor</span><input name="amount" type="number" required></label><label class="field"><span>Vencimento</span><input name="due" type="date" required></label></div><div class="modal-actions"><button class="btn primary">Salvar cobrança</button></div></form>`)}
async function runAnalysis(){toast('Analisando contratos e cobranças...');try{const j=await api('runAnalysis');state=j.state||await api();render();toast(`${j.created||0} novas oportunidades encontradas.`)}catch(e){toast(e.message,'error')}}
async function updateFinding(id,status){try{await api('updateFinding',{id,status});closeModal();await load(true);toast('Status atualizado.')}catch(e){toast(e.message,'error')}}
function recover(id){const x=state.findings.find(f=>String(f.id)===String(id));const max=remaining(x);if(max<=0)return toast('Essa oportunidade não possui saldo restante.','error');modal(`<form id="recoverForm" data-id="${id}"><div class="modal-head"><h3>Registrar recuperação</h3><button type="button" class="close" data-action="close-modal">×</button></div><div class="modal-body"><label class="field"><span>Quanto entrou de verdade?</span><input name="amount" type="number" min="0.01" max="${max}" step="0.01" value="${max}" required></label><p style="color:var(--muted);font-size:11px">Saldo máximo desta oportunidade: ${money(max)}. O Recovr mede somente o valor confirmado.</p></div><div class="modal-actions"><button class="btn primary">Confirmar valor</button></div></form>`)}
async function analyzeScope(form){const f=new FormData(form);const payload=Object.fromEntries(f);payload.value=Number(payload.value||0);payload.hours=Number(payload.hours||0);payload.hourly=Number(payload.hourly||0);const btn=form.querySelector('button');btn.disabled=true;btn.textContent='Analisando...';try{const j=await api('analyzeScope',payload);const r=j.analysis;modal(`<div class="modal-head"><div><small style="color:var(--muted)">Scope Intelligence</small><h3>${r.classification==='extra'?'Provável escopo extra':r.classification==='inside'?'Dentro do escopo':'Análise inconclusiva'}</h3></div><button class="close" data-action="close-modal">×</button></div><div class="modal-body"><div class="scope-result"><h4>${Math.round(r.confidence)}% de confiança</h4><p>${esc(r.reason)}</p></div><h4>Base contratual</h4><div class="evidence"><p>${esc(r.contract_evidence||'Escopo cadastrado no contrato.')}</p></div><h4>Valor potencial</h4><div class="calc">${r.value>0?money(r.value):'Ainda não precificado — o Recovr não inventa valor.'}</div></div><div class="modal-actions">${r.classification==='extra'?`<button class="btn primary" data-action="create-scope-finding" data-payload='${esc(JSON.stringify({...payload,...r}))}'>Criar oportunidade</button>`:'<button class="btn primary" data-action="close-modal">Concluir</button>'}</div>`)}catch(e){toast(e.message,'error')}finally{btn.disabled=false;btn.textContent='✦ Comparar com contrato'}}
async function onSubmit(e){if(e.target.id==='contractForm'){e.preventDefault();const f=new FormData(e.target);try{await api('addContract',Object.fromEntries(f));closeModal();await load(true);toast('Contrato salvo.')}catch(x){toast(x.message,'error')}}if(e.target.id==='receivableForm'){e.preventDefault();const f=new FormData(e.target);try{await api('addReceivable',Object.fromEntries(f));closeModal();await load(true);toast('Cobrança salva.')}catch(x){toast(x.message,'error')}}if(e.target.id==='recoverForm'){e.preventDefault();const f=new FormData(e.target);try{await api('recover',{id:e.target.dataset.id,amount:Number(f.get('amount'))});closeModal();await load(true);toast('Recuperação registrada.')}catch(x){toast(x.message,'error')}}if(e.target.id==='scopeForm'){e.preventDefault();analyzeScope(e.target)}}
async function click(e){const v=e.target.closest('[data-view]')?.dataset.view;if(v){setView(v);return}const el=e.target.closest('[data-action],[data-finding]');if(!el)return;if(el.dataset.finding){findingModal(el.dataset.finding);return}const a=el.dataset.action;const id=el.dataset.id;if(a==='open-app')openApp();if(a==='toggle-nav')$('.sidebar').classList.toggle('open');if(a==='refresh')load();if(a==='run-analysis')runAnalysis();if(a==='close-modal')closeModal();if(a==='new-contract')newContract();if(a==='new-receivable')newReceivable();if(a==='start-finding')updateFinding(id,'action');if(a==='dismiss-finding')updateFinding(id,'dismissed');if(a==='recover-finding')recover(id);if(a==='create-scope-finding'){try{await api('createScopeFinding',JSON.parse(el.dataset.payload));closeModal();await load(true);toast('Oportunidade de escopo criada.')}catch(x){toast(x.message,'error')}}if(a==='contract-ai'){const input=document.createElement('input');input.type='file';input.accept='application/pdf';input.onchange=async()=>{const file=input.files[0];if(!file)return;if(file.size>4_000_000)return toast('PDF acima de 4 MB nesta versão.','error');const data=await new Promise((ok,err)=>{const r=new FileReader();r.onload=()=>ok(r.result.split(',')[1]);r.onerror=err;r.readAsDataURL(file)});try{toast('IA lendo o contrato...');const j=await api('analyzeContract',{filename:file.name,file_data:data});const x=j.analysis;const form=$('#contractForm');form.client.value=x.client_name||'';form.value.value=x.monthly_value||'';form.end.value=x.end_date||'';form.adjustment.value=x.adjustment_index||'';form.last_adjustment.value=x.last_adjustment_date||'';form.scope.value=x.scope||'';toast('Contrato lido. Revise os campos antes de salvar.')}catch(x){toast(x.message,'error')}};input.click()}}
function markLandingAsDemo(){const live=$('.hero-card .live');const head=$('.hero-card-head span:first-child');if(live)live.textContent='● DEMONSTRAÇÃO';if(head)head.textContent='Exemplo de receita potencialmente perdida'}
document.addEventListener('click',click);
document.addEventListener('submit',onSubmit);
markLandingAsDemo();
if(location.hash==='#app')openApp();