(()=>{
  const nativeFetch=window.fetch.bind(window),state={loaded:false,user:null,org:null,role:null};
  window.RecovrAuth=state;
  window.fetch=async(input,init)=>{
    let next=input,url=typeof input==='string'?input:input?.url||'';
    if(typeof input==='string'&&(input==='/api/app'||input.startsWith('/api/app?')))next=input.replace('/api/app','/api/app-v09');
    const r=await nativeFetch(next,init);
    if(r.status===401&&String(next).includes('/api/app-v09')){state.user=null;state.org=null;state.role=null;showAuth('login')}
    return r;
  };
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  async function authApi(action,payload={}){const r=await nativeFetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha na autenticação');apply(j);return j}
  function apply(j){state.loaded=true;state.user=j?.user||null;state.org=j?.org||null;state.role=j?.role||null;syncFooter()}
  async function refresh(){try{const r=await nativeFetch('/api/auth',{cache:'no-store'}),j=await r.json();apply(j)}catch{state.loaded=true;state.user=null;state.org=null}}
  function ensureStyle(){if(document.getElementById('recovr-auth-style'))return;const s=document.createElement('style');s.id='recovr-auth-style';s.textContent=`.ra-back{position:fixed;inset:0;z-index:500;background:rgba(0,0,0,.78);display:grid;place-items:center;padding:18px;backdrop-filter:blur(8px)}.ra-card{width:min(460px,100%);background:#0d1219;border:1px solid #293441;border-radius:18px;box-shadow:0 25px 80px rgba(0,0,0,.5);padding:24px;color:#f3f6fa;font-family:Inter,system-ui,sans-serif}.ra-brand{display:flex;align-items:center;gap:10px;font-weight:900;letter-spacing:.14em;margin-bottom:28px}.ra-mark{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:#65f5b7;color:#04110c;letter-spacing:0}.ra-card h2{margin:0 0 7px;font-size:25px}.ra-card>p{margin:0 0 22px;color:#8994a4;line-height:1.55;font-size:13px}.ra-field{display:flex;flex-direction:column;gap:6px;margin-top:12px}.ra-field span{font-size:11px;color:#a8b3c1;font-weight:750}.ra-field input{border:1px solid #2a3542;background:#080d13;color:white;border-radius:10px;padding:12px;outline:none}.ra-field input:focus{border-color:#4c9b7d}.ra-btn{width:100%;border:0;border-radius:10px;padding:12px 14px;margin-top:18px;background:#65f5b7;color:#04110b;font-weight:850;cursor:pointer}.ra-btn:disabled{opacity:.55;cursor:wait}.ra-switch{margin-top:16px;text-align:center;color:#8994a4;font-size:12px}.ra-link{border:0;background:none;color:#65f5b7;cursor:pointer;font-weight:750}.ra-error{display:none;margin-top:12px;border:1px solid #5d3035;background:#1b0f12;color:#ffc1c5;border-radius:9px;padding:10px;font-size:12px}.ra-close{float:right;border:0;background:transparent;color:#778393;font-size:20px;cursor:pointer}.ra-note{margin-top:14px;color:#687587;font-size:10px;line-height:1.5}.ra-logout{border:0;background:transparent;color:#7f8b9a;font-size:10px;cursor:pointer;padding:4px 0}.ra-logout:hover{color:#fff}`;document.head.appendChild(s)}
  function shell(inner,closable=true){ensureStyle();document.getElementById('recovr-auth-root')?.remove();const root=document.createElement('div');root.id='recovr-auth-root';root.className='ra-back';root.innerHTML=`<div class="ra-card">${closable?'<button class="ra-close" data-ra="close">×</button>':''}<div class="ra-brand"><span class="ra-mark">R</span>RECOVR</div>${inner}</div>`;document.body.appendChild(root);root.addEventListener('click',e=>{if(e.target.dataset.ra==='close')root.remove();if(e.target.dataset.ra==='login')showAuth('login');if(e.target.dataset.ra==='register')showAuth('register')});return root}
  function error(root,msg){const el=root.querySelector('.ra-error');el.textContent=msg;el.style.display='block'}
  function showAuth(mode='login'){
    const register=mode==='register';const root=shell(`<h2>${register?'Crie sua conta':'Bem-vindo de volta'}</h2><p>${register?'Comece a monitorar receita perdida da sua empresa.':'Entre para acessar seu workspace do Recovr.'}</p><form id="ra-form">${register?'<label class="ra-field"><span>Seu nome</span><input name="name" autocomplete="name" required></label>':''}<label class="ra-field"><span>E-mail</span><input name="email" type="email" autocomplete="email" required></label><label class="ra-field"><span>Senha</span><input name="password" type="password" minlength="8" autocomplete="${register?'new-password':'current-password'}" required></label><div class="ra-error"></div><button class="ra-btn">${register?'Criar conta':'Entrar'}</button></form><div class="ra-switch">${register?'Já possui conta?':'Ainda não possui conta?'} <button class="ra-link" data-ra="${register?'login':'register'}">${register?'Entrar':'Criar conta'}</button></div><div class="ra-note">Sua sessão fica protegida em cookie HttpOnly. A senha não é armazenada em texto puro.</div>`);
    root.querySelector('#ra-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('.ra-btn'),f=Object.fromEntries(new FormData(e.target));b.disabled=true;b.textContent=register?'Criando...':'Entrando...';try{await authApi(register?'register':'login',f);if(state.org){root.remove();replayOpen()}else showOnboarding()}catch(x){error(root,x.message)}finally{b.disabled=false;b.textContent=register?'Criar conta':'Entrar'}})
  }
  function showOnboarding(){
    const root=shell(`<h2>Agora, sua empresa</h2><p>O Recovr separa cada workspace. Informe os dados básicos para começar vazio e seguro.</p><form id="ra-company"><label class="ra-field"><span>Nome da empresa</span><input name="name" required></label><label class="ra-field"><span>CNPJ <small>(opcional)</small></span><input name="cnpj" inputmode="numeric" maxlength="18"></label><div class="ra-error"></div><button class="ra-btn">Criar workspace</button></form><div class="ra-note">Você poderá importar contratos e cobranças depois. Nenhum dado da demonstração é copiado para sua empresa.</div>`,false);
    root.querySelector('#ra-company').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('.ra-btn'),f=Object.fromEntries(new FormData(e.target));b.disabled=true;b.textContent='Criando workspace...';try{await authApi('createOrganization',f);root.remove();replayOpen()}catch(x){error(root,x.message)}finally{b.disabled=false;b.textContent='Criar workspace'}})
  }
  function replayOpen(){setTimeout(()=>{const b=document.querySelector('[data-action="open-app"]');if(b)b.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}))},0)}
  function syncFooter(){const foot=document.querySelector('.side-foot');if(!foot||!state.user)return;const av=foot.querySelector('.avatar'),box=foot.querySelector('div'),strong=box?.querySelector('strong');if(av)av.textContent=String(state.user.name||state.user.email).split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();if(strong)strong.textContent=state.org?.name||state.user.name;if(!foot.querySelector('.ra-logout')){const out=document.createElement('button');out.className='ra-logout';out.textContent='Sair';out.addEventListener('click',async()=>{try{await authApi('logout');document.getElementById('app')?.classList.add('hidden');document.getElementById('landing')?.classList.remove('hidden');history.replaceState(null,'',location.pathname);apply({})}catch{}});box?.appendChild(out)}}
  document.addEventListener('click',async e=>{
    const open=e.target.closest?.('[data-action="open-app"]');if(!open)return;
    if(!state.loaded){e.preventDefault();e.stopImmediatePropagation();await refresh();if(!state.user)return showAuth('login');if(!state.org)return showOnboarding();return replayOpen()}
    if(!state.user){e.preventDefault();e.stopImmediatePropagation();return showAuth('login')}
    if(!state.org){e.preventDefault();e.stopImmediatePropagation();return showOnboarding()}
    syncFooter();
  },true);
  refresh().then(()=>{if(location.hash==='#app'&&(!state.user||!state.org)){history.replaceState(null,'',location.pathname);state.user?showOnboarding():showAuth('login')}syncFooter()});
  const ux=document.createElement('script');ux.src='/contract-ux.js';ux.defer=true;document.head.appendChild(ux);
})();
